### ISSUE TITLE
Compilation fails with VS2015

### ISSUE THREAD

**Issue by mathstuf** [OpenGeoscience/vtkMap#89]
Not sure what's up. Looks like it just needs a sweep. At least this error is showing up:

```
error C3861: 'back_inserter': identifier not found
```

which indicates that `<iterator>` isn't being included.

Cc: @johnkit

**Comment by johnkit** [comment]
Yep, including `<iterator>` seems to fix *that* problem. I'll do a PR shortly.

The next compile problem, however, leaves me a bit perplexed. Compiling vtkRasterFeature.cxx fails because vtkIOStream cannot open the include file 'iostream'. If you have any ideas on that one, please let me know...

![windowserror](https://user-images.githubusercontent.com/5559383/28843409-0ffe7b24-76cf-11e7-9ce4-bf86e2863876.png)

**Comment by johnkit** [comment]
Oops, forgot to use a VS2017 terminal.

**Comment by mathstuf** [comment]
Sorry, it's actually 2015 :) . But yep :) .
